name: New Release

on:
  release:
    types: [created]

jobs:
  build:
    # runs-on: ${{matrix.os}}
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Git checkout
      - uses: actions/checkout@v4
      - name: Setup rust
        uses: ATiltedTree/setup-rust@v1.0.5
        with:
          rust-version: stable
      - name: Compile
        run: cargo check