name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build linux arm
      run: cargo build -r --target aarch64-unknown-linux-gnu
    - name: Build linux desktop
      run: cargo build -r --target x86_64-unknown-linux-gnu
